// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBiG7fLNWtJC-rblZGla4lwfde3UofYw',
    appId: '1:133529124403:web:35e40d5c988785605aad46',
    messagingSenderId: '133529124403',
    projectId: 'talkdeals-ddaa8',
    authDomain: 'talkdeals-ddaa8.firebaseapp.com',
    storageBucket: 'talkdeals-ddaa8.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkkq4iCJ-eCn0WqRB9Hq8Pn0QSEpWLsyM',
    appId: '1:133529124403:android:d37a1d051e2550ce5aad46',
    messagingSenderId: '133529124403',
    projectId: 'talkdeals-ddaa8',
    storageBucket: 'talkdeals-ddaa8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC05wi9a8BhHJmY4Hrqew3lccnvfvYCMtc',
    appId: '1:133529124403:ios:18a872e640aeadd85aad46',
    messagingSenderId: '133529124403',
    projectId: 'talkdeals-ddaa8',
    storageBucket: 'talkdeals-ddaa8.firebasestorage.app',
    iosBundleId: 'com.example.talkdeals',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC05wi9a8BhHJmY4Hrqew3lccnvfvYCMtc',
    appId: '1:133529124403:ios:18a872e640aeadd85aad46',
    messagingSenderId: '133529124403',
    projectId: 'talkdeals-ddaa8',
    storageBucket: 'talkdeals-ddaa8.firebasestorage.app',
    iosBundleId: 'com.example.talkdeals',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjBiG7fLNWtJC-rblZGla4lwfde3UofYw',
    appId: '1:133529124403:web:2b4584f90630c5815aad46',
    messagingSenderId: '133529124403',
    projectId: 'talkdeals-ddaa8',
    authDomain: 'talkdeals-ddaa8.firebaseapp.com',
    storageBucket: 'talkdeals-ddaa8.firebasestorage.app',
  );
}
